typography_spectrum: 0.04482694761827588
color:
  brandStrength: 0.10593253746628761
  lightness: 0.8673841974232346
  saturation: 0.721158069325611
  rhythmicContrast: 0.494335773633793
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.3283519227989018
author:
  name: Roberto Maria Grassi
  email: robertomariagrassi@icloud.com
  url: 'https://fr.wikipedia.org/wiki/Roberto_Maria_Grassi'
name: Montsalvat
title: Roberto Maria Grassi
description: filming live shows
