typography_spectrum: 0.20018579764291644
color:
  brandStrength: 0.29979850910604
  lightness: 0.25847163517028093
  saturation: 0.2718395898118615
  rhythmicContrast: 0.26206502923741937
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.19418861041776836
author:
  name: Roberto Maria Grassi
  email: robertomariagrassi@icloud.com
  url: 'https://fr.wikipedia.org/wiki/Roberto_Maria_Grassi'
name: Montsalvat
title: Roberto Maria Grassi
description: filming live shows
